=== epilot-dev/docs/static/schemas/asset-jsonschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_schema"
  ],
  "properties": {
    "_schema": {
      "readOnly": true,
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$",
      "example": "asset",
      "description": "URL-friendly identifier for the entity schema"
    },
    "_id": {
      "readOnly": true,
      "type": "string",
      "format": "uuid",
      "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "description": "Unique identifier for the entity"
    },
    "_org": {
      "type": "string",
      "description": "Organization Id the entity belongs to",
      "readOnly": true,
      "example": "123"
    },
    "_title": {
      "readOnly": true,
      "type": "string",
      "nullable": true,
      "example": "Entity Title",
      "description": "Generated title for the entity based on schema title_template"
    },
    "_tags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "family:label"
      ],
      "description": "Entity Labels"
    },
    "_purpose": {
      "$ref": "#/definitions/PurposeAttribute",
      "description": "Purposes"
    },
    "title": {
      "type": "string",
      "description": "Asset Title"
    },
    "customer": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Customer"
    },
    "installation_address": {
      "$ref": "#/definitions/BaseRelationRef",
      "description": "Installation Address"
    },
    "asset_number": {
      "type": "string",
      "description": "Asset Number"
    },
    "serial_number": {
      "type": "string",
      "description": "Serial Number"
    },
    "manufacturer": {
      "type": "string",
      "description": "Manufacturer"
    },
    "model": {
      "type": "string",
      "description": "Model"
    },
    "manufacturing_date": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "Manufacturing Date"
    },
    "maintenance_date": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "Last Maintenance Date"
    },
    "commissioning_date": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "Commissioning Date"
    },
    "installation_date": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "Installation Date"
    },
    "guarantee": {
      "type": "string",
      "description": "Guarantee: hint_helper.asset.guarantee_years"
    },
    "manual": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Manual"
    },
    "technical_data_about_installation": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Technical data about Installation"
    },
    "asset": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Assets"
    },
    "contract": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Contract"
    },
    "meter": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Meter"
    },
    "ticket": {
      "$ref": "#/definitions/BaseRelation",
      "description": "Ticket"
    },
    "asset_type": {
      "type": "string",
      "enum": [
        "Wärmepumpe",
        "Wallbox",
        "Ladesäule",
        "Solarmodul"
      ],
      "description": "Asset Type"
    },
    "upcoming_maintenance_date": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "Upcoming Maintenance Date"
    },
    "beginn_widerrufsfrist": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "Beginn Widerrufsfrist"
    },
    "ende_widerrufsfrist": {
      "type": "string",
      "format": "date",
      "example": "2025-01-01",
      "description": "Ende Widerrufsfrist"
    },
    "workflows": {
      "$ref": "#/definitions/WorkflowOverview"
    },
    "_files": {
      "$ref": "#/definitions/BaseRelation"
    },
    "_created_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity creation"
    },
    "_updated_at": {
      "readOnly": true,
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp of entity last update"
    },
    "_owners": {
      "type": "array",
      "readOnly": true,
      "items": {
        "description": "The user / organization owning this entity.\n\nNote: Owner implicitly has access to the entity regardless of ACLs.\n",
        "type": "object",
        "properties": {
          "org_id": {
            "type": "string",
            "example": "123"
          },
          "user_id": {
            "type": "string",
            "example": "456"
          }
        },
        "required": [
          "org_id"
        ]
      }
    },
    "_acl": {
      "readOnly": true,
      "type": "object",
      "description": "Access control list (ACL) for an entity. Defines sharing access to external orgs or users.",
      "additionalProperties": true,
      "properties": {
        "view": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "edit": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        },
        "delete": {
          "type": "array",
          "items": {
            "type": "string",
            "example": "org:456"
          }
        }
      }
    },
    "_manifest": {
      "readOnly": true,
      "type": "array",
      "nullable": true,
      "description": "Blueprint ID used to create/update the entity",
      "items": {
        "type": "string"
      },
      "example": [
        "123e4567-e89b-12d3-a456-426614174000"
      ]
    }
  },
  "definitions": {
    "PurposeAttribute": {
      "type": "array",
      "description": "List of purpose ids",
      "items": {
        "type": "string"
      },
      "example": [
        "7675dc56-fd1b-46ee-9c35-defe0667b32e"
      ]
    },
    "BaseUUID": {
      "type": "string",
      "format": "uuid",
      "example": "123e4567-e89b-12d3-a456-426614174000"
    },
    "BaseTags": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "string"
      },
      "example": [
        "example"
      ]
    },
    "BaseRelation": {
      "type": "object",
      "nullable": true,
      "description": "Relation to another entity",
      "properties": {
        "$relation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              }
            }
          }
        }
      }
    },
    "BaseRelationRef": {
      "type": "object",
      "nullable": true,
      "description": "Reference to a specific property of another entity",
      "properties": {
        "$relation_ref": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "entity_id": {
                "$ref": "#/definitions/BaseUUID"
              },
              "path": {
                "type": "string",
                "example": "address",
                "description": "The property of the entity (pointed by entity_id) to be used as the reference"
              },
              "_tags": {
                "$ref": "#/definitions/BaseTags"
              },
              "_id": {
                "type": "string",
                "example": "xHcOoJCa07eysJ1GaQeSb"
              }
            }
          }
        }
      }
    },
    "WorkflowStatus": {
      "type": "string",
      "enum": [
        "STARTED",
        "DONE",
        "CLOSED"
      ]
    },
    "StepType": {
      "type": "string",
      "enum": [
        "MANUAL",
        "AUTOMATION"
      ]
    },
    "StepStatus": {
      "type": "string",
      "enum": [
        "UNASSIGNED",
        "ASSIGNED",
        "COMPLETED",
        "SKIPPED",
        "IN_PROGRESS"
      ]
    },
    "PhaseInEntity": {
      "type": "object",
      "description": "Workflow phase information",
      "properties": {
        "phase_id": {
          "type": "string"
        },
        "phase_name": {
          "type": "string"
        },
        "phase_progress": {
          "type": "number"
        }
      },
      "required": [
        "phase_id",
        "phase_name",
        "phase_progress"
      ]
    },
    "WorkflowInEntity": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "definition_id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/WorkflowStatus"
        },
        "assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "progress": {
          "type": "number"
        },
        "phases_in_progress": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PhaseInEntity"
          }
        },
        "last_update_time": {
          "type": "string",
          "format": "date-time"
        },
        "upcoming_tasks_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "task_id": {
          "type": "string"
        },
        "task_name": {
          "type": "string"
        },
        "task_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "task_duedate": {
          "type": "string",
          "format": "date-time"
        },
        "task_execution_type": {
          "$ref": "#/definitions/StepType"
        },
        "task_status": {
          "$ref": "#/definitions/StepStatus"
        },
        "phase_id": {
          "type": "string"
        },
        "phase_name": {
          "type": "string"
        },
        "phase_assignees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "phase_progress": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "definition_id",
        "name",
        "status",
        "assignees",
        "last_update_time"
      ]
    },
    "WorkflowOverview": {
      "type": "object",
      "properties": {
        "primary": {
          "$ref": "#/definitions/WorkflowInEntity"
        }
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/WorkflowInEntity"
        }
      }
    }
  }
}

=== epilot-dev/docs/static/schemas/asset-example.json
{
  "_schema": "asset",
  "_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "_org": "123",
  "_title": "Entity Title",
  "_tags": [
    "family:label"
  ],
  "_purpose": [
    "7675dc56-fd1b-46ee-9c35-defe0667b32e"
  ],
  "title": "string",
  "customer": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "installation_address": {
    "$relation_ref": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "path": "address",
        "_tags": [
          "example"
        ],
        "_id": "xHcOoJCa07eysJ1GaQeSb"
      }
    ]
  },
  "asset_number": "string",
  "serial_number": "string",
  "manufacturer": "string",
  "model": "string",
  "manufacturing_date": "2025-01-01",
  "maintenance_date": "2025-01-01",
  "commissioning_date": "2025-01-01",
  "installation_date": "2025-01-01",
  "guarantee": "string",
  "manual": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "technical_data_about_installation": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "asset": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "contract": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "meter": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "ticket": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "asset_type": "Wärmepumpe",
  "upcoming_maintenance_date": "2025-01-01",
  "beginn_widerrufsfrist": "2025-01-01",
  "ende_widerrufsfrist": "2025-01-01",
  "workflows": {
    "primary": {
      "id": "string",
      "definition_id": "string",
      "name": "string",
      "status": "STARTED",
      "assignees": [
        "string"
      ],
      "progress": 0,
      "phases_in_progress": [
        {
          "phase_id": "string",
          "phase_name": "string",
          "phase_progress": 0
        }
      ],
      "last_update_time": "1970-01-01T00:00:00.000Z",
      "upcoming_tasks_assignees": [
        "string"
      ],
      "task_id": "string",
      "task_name": "string",
      "task_assignees": [
        "string"
      ],
      "task_duedate": "1970-01-01T00:00:00.000Z",
      "task_execution_type": "MANUAL",
      "task_status": "UNASSIGNED",
      "phase_id": "string",
      "phase_name": "string",
      "phase_assignees": [
        "string"
      ],
      "phase_progress": 0
    }
  },
  "_files": {
    "$relation": [
      {
        "entity_id": "123e4567-e89b-12d3-a456-426614174000",
        "_tags": [
          "example"
        ]
      }
    ]
  },
  "_created_at": "1970-01-01T00:00:00.000Z",
  "_updated_at": "1970-01-01T00:00:00.000Z",
  "_owners": [
    {
      "org_id": "123",
      "user_id": "456"
    }
  ],
  "_acl": {
    "view": [
      "org:456"
    ],
    "edit": [
      "org:456"
    ],
    "delete": [
      "org:456"
    ]
  },
  "_manifest": [
    "123e4567-e89b-12d3-a456-426614174000"
  ]
}
